Milestone 2: Mobile View portfolio Design
SimonGideon/Portfolio pull request #2
Opened 2022-07-01 20:15 UTC by SimonGideon

## Parse a Figma design to create a Mobile  UI.
In milestone two of the project, we: 
- Added work and about myself section.
- Improved mobile responsiveness at different screen widths.
- Replace png images with high-quality SVG images.

2022-07-01 21:09 UTC, vickymarz requested changes
Hi @SimonGideon , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has failed linter checks. Kindly fix the linter errors and submit again 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-01 23:40 UTC, isaacpitwa requested changes
Hi @SimonGideon  🙂 ,

You have done a tremendous job setting up your project. I really like it :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅
- Well documented Repository ✅
-  Clean and readable code base ✅

## Required changes ♻️ 

Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 23:40 UTC, isaacpitwa commented on Index.html
> +    <section class="work">
- [ ] it is required of this section to be styled using Grid layout and its components the word card content styled using flex. kindly add grid layout styles to this section.

2022-07-01 23:40 UTC, isaacpitwa commented on Index.html
> +                </div>
- [ ] it would be more useful to use the `ul` tag instead of div to offer improved project semantics and SEO for your website. Kindly consider making this change

2022-07-01 23:40 UTC, isaacpitwa commented on Index.html
> +                </li>
Great job working on achieving this section 👏🏽
unfortunately some features are missing in your design  to match the Figma design

**Your Design**
<img width="183" alt="Screenshot 2022-07-02 at 02 15 50" src="https://user-images.githubusercontent.com/31113416/176976948-57a35861-81a3-420e-a622-85cd6c3d6a68.png">

**Figma design**
<img width="370" alt="Screenshot 2022-07-02 at 02 17 45" src="https://user-images.githubusercontent.com/31113416/176976957-5d3b1895-13b8-4a05-b7f7-a44009d5aecc.png">


- [ ]  Kindly adjust your design to have a background and a curved corner as indicated in the screenshots above.
- [ ] please update your design to have missing drop-down  icons on the grouping of this section. check screenshits below.

**your design**
<img width="187" alt="Screenshot 2022-07-02 at 02 22 56" src="https://user-images.githubusercontent.com/31113416/176977254-da97976d-0abc-4046-9c12-4f8fb3bf1208.png">

**Figma design**
<img width="368" alt="Screenshot 2022-07-02 at 02 21 16" src="https://user-images.githubusercontent.com/31113416/176977437-5974399b-7083-4442-85f9-c485e60f6d1d.png">


- [ ] Please note that the categories  **Frameworks** and **Skills** do not have the same styling as the languages. kindly update the styles to match the Figma file.

2022-07-01 23:40 UTC, isaacpitwa commented on Index.html
> +                <p>LET'S CONNECT</p>
- [ ] Kindly use an `h2..h6` instead of  a `p` in order to improve the semantics as this is a heading section title instead of a paragraph

2022-07-01 23:40 UTC, isaacpitwa commented on Index.html
> +            </ul>
- [ ]  As part of the project requirements, it is required to have The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

2022-07-01 23:40 UTC, isaacpitwa commented on style.css
>    }
- [ ] For this section in the project, it is required to complete its styling using a flexbox layout. this will help improve responsiveness across different mobile device sizes compared to fixed sizes used.

2022-07-02 10:26 UTC, KayLemba requested changes
Hi @ElsonOtake   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
- Check the comments under the review in the inline comments.
- Please add a screenshot showcasing your UI  to read README file to make it look more proffessional
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-02 10:26 UTC, KayLemba commented on Index.html
> +                <li>
Please kindly implent this change as requested by previous code reviewer 

Great job working on achieving this section 👏🏽
unfortunately some features are missing in your design to match the Figma design

Your Design
![Screenshot from 2022-07-02 14-18-37](https://user-images.githubusercontent.com/79506105/176996425-56380328-691a-46ce-943c-df6614404c4c.png)



Please follow this figma design
Figma design

![Screenshot from 2022-07-02 14-22-01](https://user-images.githubusercontent.com/79506105/176996531-cc8911b1-ee59-4442-a281-99b0df1f6930.png)

 Kindly adjust your design to have a background and a curved corner as indicated in the screenshots above.
 please update your design to have missing drop-down icons on the grouping of this section. check screenshits below.

2022-07-04 23:28 UTC, mwanawabangona requested changes
## Status: Changes Required

 ## Hello there @SimonGideon 👋🏽

###  You have done an amazing job so far! 👏🏽 👏🏽
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand:


## Highlights
* ✅  No linter errors heavy_check_mark
* ✅  Repo looks professional briefcase
* ✅  Solid pull request scroll
* ✅  Good use of flexbox 🧐
* ✅  Good quality commits

## Required Changes
 _**Check the comments under the review.**_

 ## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @mwanawabangona in your question so I can receive the notification.
>
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
>
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 23:28 UTC, mwanawabangona commented on Index.html
>                  </div>
- [ ] `required`
- The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` 
- :pray: please i suggest you add the list `ul` and each of them a `li`

2022-07-04 23:28 UTC, mwanawabangona commented on Index.html
>                  </div>
- [ ] `required` 
- The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` 
- :pray: please i suggest you add the list `ul` and each of them a `li`

2022-07-04 23:28 UTC, mwanawabangona commented on Index.html
>                  </div>
- [ ] `required`
- The list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li` 
- :pray: please i suggest you add the list `ul` and each of them a `li`

2022-07-05 12:16 UTC, ishimwezachee commented on Index.html
> +    <section class="work">
done

2022-07-05 12:27 UTC, ishimwezachee requested changes
Hi @SimonGideon, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

 ## Highlights
All linters are passing ✅
Correct use of GitHub flow ✅
Well-documented Repository ✅
Clean and readable code base ✅

 ## Required Changes ♻️
Please implement these changes requested by the previous reviewer, they are required on your project 


- [ ]  List the project technologies using `ul `; each should be in `li` as suggested by previous reviewers. for more [information](https://www.w3schools.com/html/html_lists.asp)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 16:08 UTC, SimonGideon commented
@ishimwezachee [ishimwezachee](https://github.com/ishimwezachee)
Help me fix out this.

2022-07-05 19:32 UTC, Kandy-Peter approved these changes
Hi @SimonGideon,

### APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

##  Optional suggestion
 
# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 14:04 UTC, merged