Milestone #4 Desktop view
SimonGideon/Portfolio pull request #4
Opened 2022-07-14 20:32 UTC by SimonGideon

This is the desktop version of my portfolio

2022-07-14 22:38 UTC, vickymarz requested changes
Hi @SimonGideon , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 22:38 UTC, vickymarz commented on style.css
>    list-style: none;
- [ ] I think it would be better to align the social icons to be on the same line with the headline contents. This is to ensure that your website follows the same flow which will make your website a lot nicer 😎 .

![image](https://user-images.githubusercontent.com/63473584/179096135-4487e13e-aaf7-493c-a4c8-d5240610d830.png)

2022-07-14 22:38 UTC, vickymarz commented on Index.html
> +            <div class="card-content">
- [ ] I think it will be nice to align your project card's content to match the chosen Figma design template. I can see that your project descriptions are at the center beside the project image but they are at the top in the Figma design. Removing `align-items: center` for the desktop view should fix it. Kindly adjust it 👍 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/179097333-e6e507c1-1f42-4568-a016-12b1eccade66.png)  | ![image](https://user-images.githubusercontent.com/63473584/179097484-04b44170-0bd2-4771-947e-6519cc344340.png)  |

2022-07-15 15:11 UTC, vechicin requested changes
# Hi @SimonGideon ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing most of the changes required by the previous reviewer

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 15:11 UTC, vechicin commented on Index.html
> +                        </form>
While you did implement the previous reviewer's requirements you didn't do so properly. Make sure you still fix the margins between each input field in the mobile version and that you keep their width consistent with the Figma design.

Your design:
<img width="225" alt="Screen Shot 2022-07-15 at 10 03 23" src="https://user-images.githubusercontent.com/82426682/179250840-8040258a-814d-4b2a-93a6-2d1ba70ce710.png">

Figma design:
<img width="307" alt="Screen Shot 2022-07-15 at 10 06 26" src="https://user-images.githubusercontent.com/82426682/179251423-a27f08a2-6da3-4173-8a2b-39483d519c6f.png">

Additionally, make sure the button is centered in the desktop version, it is still slightly slanted to the right.

<img width="1440" alt="Screen Shot 2022-07-15 at 10 09 58" src="https://user-images.githubusercontent.com/82426682/179252102-a5630b64-0a7d-4417-85fd-62c6f34144e7.png">

2022-07-15 15:28 UTC, SimonGideon commented
@[vechicin](https://github.com/vechicin)
Please Check the last commit before I submit my last review

2022-07-15 16:07 UTC, vechicin requested changes
# Hi @SimonGideon ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing some of the previous requirements.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 16:07 UTC, vechicin commented on style.css
>  }
This background is now not properly placed in the desktop version because you changed the `background-image` to a `<img>` tag. Please revert it to the way it was.

<img width="1440" alt="Screen Shot 2022-07-15 at 11 05 50" src="https://user-images.githubusercontent.com/82426682/179262822-ba650d01-782e-48a5-91e4-4780a70e8698.png">

2022-07-15 16:37 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @SimonGideon , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 17:34 UTC, merged